### ISSUE TITLE
Refactor scripts

### ISSUE THREAD

**Issue by rcannood** [viash-io/website#13]
Scripts `bin/scripts/generate_cli_schema_export_pages.py` and `bin/scripts/generate_config_schema_export_pages.py` need to be refactored. Things to work on:

* [x] Make Viash components for the scripts
* [x] Make the code more functional
* [x] Add more type annotations
* [ ] Check to what degree the `reference/` folder is actually being fully auto-generated by these scripts; that is, remove the `reference/` folder, run the scripts and see what files are missing. For instance, it seems the following files are not but should be auto-generated:
  - `reference/reference.yml`
  - `reference/overview.qmd`
  - `reference/config_modding.qmd`
* [x] Optional: Use jinja templates (similar to quarto/generate_documentation_qmd)

**Comment by Grifs** [comment]
When removing the `reference/` folder and recreating it by using the `render_pages.sh` script, these files are missing:

reference/_metadata.yml
reference/cli/index.qmd
reference/cli/template.ejs
reference/config_mods/index.qmd
reference/index.qmd
reference/reference.css
reference/reference.lua
reference/reference.yml
reference/viash_code_block/index.qmd

**Comment by Grifs** [comment]
Update: Only the files directly under the reference folder are still fixed.

```
reference/_metadata.yml
reference/index.qmd
reference/reference.css
reference/reference.lua
reference/reference.yml
```

**Comment by Grifs** [comment]
Update # 2, After PR #62, only `reference/index.qmd` is still static.
`reference.yml` is generated, others were removed.

**Comment by Grifs** [comment]
@rcannood WDYT? Shall we close this issue?

**Comment by rcannood** [comment]
LGTM!
