### ISSUE TITLE
In reference docs, point to correct location directly

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/website#2]
For instance, on the [`viash ns` reference page](https://viash-io.github.io/new_website/documentation/reference/viash/ns.html#viash-ns-test), it says:

> Modify a viash config at runtime using a custom DSL. For more information, see the online documentation.

It would be good to have a hyperlink to the correct page.

**Comment by BlackDragonBE** [comment]
I'm going to solve this by replacing certain terms with hyperlinks via scripting. Adding markdown links to the `descr` would result in a very messy terminal output.

As the reference pages are already generated via scripts, this shouldn't be too complex:

- [ ] Create list of keywords and replacements
- [ ] Implement replacing in reference generating scripts
- [ ] Check outputs for errors

**Comment by BlackDragonBE** [comment]
Fixed in [f39575e](https://github.com/viash-io/website/commit/f39575e6cf0d9d51ee3389b695e06b3d50be7d6d)
