### ISSUE TITLE
Restructure "Reference"

### ISSUE THREAD

**Issue by rcannood** [viash-io/website#23]
This site should contain reference documentation on the following topics:
* Viash CLI commands (`/reference/cli`:
  - `viash build` (`/reference/cli/build`)
  - `viash run` (`/reference/cli/run`)
  - `viash ns build` (`/reference/cli/ns/build`)
  - `viash ns test` (`/reference/cli/ns/test`)
  - ...
* Viash config spec (`/reference/config`):
  - `config` (/reference/config/index): overview of the config
  - `functionality` (/reference/config/functionality/index): overview of the functionality
    - `arguments` (/reference/config/functionality/arguments/index): overview of the different arguments
      - `string` (/reference/config/functionality/arguments/string): string argument
      - `file` (/reference/config/functionality/arguments/file): file argument
      - `double` (/reference/config/functionality/arguments/double): double argument
  - ...
  - `platforms` (/reference/config/platforms/index): overview of the platforms
    - `native` (/reference/config/platforms/native): overview of the native platform
    - `docker` (/reference/config/platforms/docker/index): overview of the docker platform
      - `setup` (/reference/config/platforms/docker/setup/index): overview of the different setup commands
        - `apk` (/reference/config/platforms/docker/setup/apk): apk docs
        - `apt` (/reference/config/platforms/docker/setup/apt): apt docs
        - `docker` (/reference/config/platforms/docker/setup/docker): docker docs
    - `nextflow` (/reference/config/platforms/nextflow): overview of the nextflow platform
      - `directives` (/reference/config/platforms/nextflow/directives/): overview of the nextflow directives
* Config mods (`/reference/config_mods`)
* Viash code block (`/reference/viash_code_block`)?
  - Input arguments `par` (`/reference/viash_code_block/par`)?
  - Meta arguments `meta` (`/reference/viash_code_block/meta`)?
* Project config (`/reference/project`)

**Comment by DriesSchaumont** [comment]
Would also be nice to add links between the reference and the guide. A user might find the reference too concise and a link to the guide might be helpful in these cases.
