### ISSUE TITLE
Bullet points can become hard to read

### ISSUE THREAD

**Issue by tverbeiren** [viash-io/website#3]
For instance, under *auto* in https://viash-io.github.io/new_website/documentation/reference/config/platforms/nextflowVdsl3Platform.html.

Probably a table is a better representation here.

**Comment by BlackDragonBE** [comment]
Needs to be edited in the viash repo. I'll create a PR for it.

**Comment by BlackDragonBE** [comment]
- Fixed in this Viash PR: https://github.com/viash-io/viash/pull/241
- Fixed in this website draft commit: https://github.com/viash-io/website/commit/607253d8d0a1387e8449ac51766a057aba5da753
