### ISSUE TITLE
The information on argument types could be merged to a single page

### ISSUE THREAD

**Issue by rcannood** [viash-io/website#5]
We could combine all of the parameter descriptions and describing whether a field is applicable to that argument type or not.

**Comment by BlackDragonBE** [comment]
@rcannood I've started working on this, but the more I look at the potential result, the more I'm getting doubts if this is the right way to go:

- I'm not sure if there's a lot of benefit for our website visitors to have a single page vs a page per argument type:
  * Searchability is the same as the website search results finds matches in titles, headers and even content
  * A page containing all properties will require more scrolling. Even more so if there are more examples needed per property.
  * Linking to a property will be the the same, just a link to an anchor
  * Linking to a a certain argument type won't be possible anymore once merged, only to the general arguments page
  * The sole benefit of a merged page I can think of is it's easier to link to when talking about arguments as a whole. This can be worked around though by providing an index/overview page with links to the different argument types.
- While some properties like `alternatives` and `required` are fairly easy to merge together with one description and a generic example, others like `multiple` and 'choices' benefit from their unique examples. A possible workaround to this would be to provide multiple examples for these.
- Every argument type has a description and an example on how to use it. I'm not sure where to put these on a merged page, except for a list of descriptions for every type and a yaml snippet that includes examples for each type.
- `name` is slightly different for boolean_true/false types compared to other arguments as it can be used as a flag: `executable_name --foo` vs executable_name --foo=value`. Once merged, there won't a distinction between these without adding custom text to explain this (which I'd like to avoid).

The merge also requires quite some effort as the argument page generation will need its own custom function to gather all argument properties, compare them to eachother, merge the duplicates, label the properties by argument type and then finally create the page. This in itself isn't an issue and can be a nice coding excercise if the result is worth it of course, but it will take quite some time to get right.

Let me know your thoughts.

**Comment by rcannood** [comment]
Closing this issue
