### ISSUE TITLE
Defining dependencies for the docker platform using setup is unclear.

### ISSUE THREAD

**Issue by DriesSchaumont** [viash-io/website#7]
Using setup is currently the supported way of defining depencencies for the docker platform (as opposed to for example 'apt', which is deprecated). However, the documentation on how to use `setup` is very limited: https://viash.io/documentation/reference/config/platforms/dockerPlatform.html#setup

e.g. what is the syntax? + An example would be nice

**Comment by BlackDragonBE** [comment]
This is already on my to-do list, but it's a good call to add it here to keep track of.
My plan is to have a seperate page that will list the supported requirements per package type.

**Comment by BlackDragonBE** [comment]
@DriesSchaumont 
I've added seperate pages for now, as I need to refactor the generation script to allow for page merging, but at least the information is there:

https://viash.io/documentation/reference/config/platforms/dockerPlatform.html#setup

**Comment by BlackDragonBE** [comment]
@DriesSchaumont 
The setup requirements are now on a single page: https://viash.io/documentation/reference/config/requirements.html
The text and examples are pretty bare bones, but they can be expanded upon by modyfing the viash source code.
