### ISSUE TITLE
Modify main script path in Viash Quickstart

### ISSUE THREAD

**Issue by ghost** [viash-io/website#78]
Currently, the Viash Quickstart (https://viash.io/quickstart/), section **3.  Run the pipeline** contains input arguments:

<img width="824" alt="image" src="https://github.com/viash-io/website/assets/161341470/e4b2fb60-113d-4a7f-b4d9-7d769482c744">

`nextflow run .
  -main-script template/workflow/main.nf
  -with-docker
  --input resources_test/file*.tsv
  --publish_dir output`

the main script path should be changed to `target/nextflow/template/workflow/main.nf` as components are built in the **target** directory in the revious step by default:

`nextflow run .
  -main-script target/nextflow/template/workflow/main.nf
  -with-docker
  --input resources_test/file*.tsv
  --publish_dir output`

**Comment by tverbeiren** [comment]
Good catch! Can you please create a PR for this?
