### ISSUE TITLE
Use XDG base directory to install viash

### ISSUE THREAD

**Issue by KaiWaldrant** [viash-io/website#92]
With updating to quarto v1.5 I noticed a change in install folder.

They are using the `~/.local/bin` directory now. quarto-dev/quarto-web#1118

Seems like this is the new way to keep a tidy home dir and with the latest os this is automatically added to PATH.

https://github.com/viash-io/website/blob/d8d7a91a625aa8af1d822baefadba6e123911610/installation/index.qmd#L48

suggestion:
```
 wget -qO- dl.viash.io | bash; mv viash $HOME/.local/bin 
```

WDYT?

**Comment by rcannood** [comment]
feel free to turn this into a PR!
